// Package selfsigned creates and reuses a self-signed TLS certificate for
// deployments without a CA-issued one (home servers, private networks).
//
// The certificate is not trusted by any operating system. Clients are expected
// to pin its SHA-256 fingerprint after the user has confirmed it out of band,
// which is why the fingerprint is returned and logged at startup.
package selfsigned

import (
	"bytes"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"crypto/tls"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// File names inside server.tls.self_signed_dir.
const (
	CertFileName = "selfsigned.crt"
	KeyFileName  = "selfsigned.key"
)

const (
	// A generated certificate is valid this long. Clients re-confirm the
	// fingerprint after a rotation, so it is kept long to make that rare.
	validity = 2 * 365 * 24 * time.Hour
	// An existing certificate is replaced once fewer than this remains.
	renewBefore = 30 * 24 * time.Hour
	// NotBefore is set slightly in the past to tolerate client clock skew.
	clockSkew = time.Hour

	// subjectCommonName marks certificates made by this package.
	subjectCommonName = "CalSnap self-signed"
)

// Options describe where the certificate lives and what it must cover.
type Options struct {
	// CertFile and KeyFile are the PEM files to use. Their directories are
	// created when missing.
	CertFile string
	KeyFile  string
	// Managed says that the server owns both files (the self_signed_dir mode):
	// an unusable pair is then always replaced. Without it the files may be an
	// operator's own certificate, so they are only created when both are
	// missing and are replaced only if this package generated them.
	Managed bool
	// Hosts are DNS names and IP addresses put into the subject alternative
	// names. Duplicates and empty entries are ignored.
	Hosts []string
	// Now returns the current time.
	Now func() time.Time
}

// Result describes the certificate that is in use.
type Result struct {
	CertFile string
	KeyFile  string
	// Fingerprint is the SHA-256 of the DER certificate as colon-separated
	// upper-case hex, the format the app shows to the user.
	Fingerprint string
	NotAfter    time.Time
	// Created is true when a new certificate was generated by this call.
	Created bool
}

// Ensure returns the certificate stored in the configured files, generating a
// new one when they are missing (or, for files this package generated, when the
// pair is unreadable or expires soon). A valid certificate is never
// regenerated because its fingerprint is pinned by clients.
func Ensure(opts Options) (Result, error) {
	if opts.CertFile == "" || opts.KeyFile == "" {
		return Result{}, errors.New("self-signed certificate paths are empty")
	}
	if opts.Now == nil {
		opts.Now = time.Now
	}
	now := opts.Now()

	leaf, loadErr := loadPair(opts.CertFile, opts.KeyFile)
	if loadErr == nil {
		// The operator's own certificate is used as it is, whatever its
		// validity: renewing it is the operator's job.
		if validFor(leaf, now, renewBefore) || (!opts.Managed && !isGenerated(leaf)) {
			return result(opts, leaf, false), nil
		}
		loadErr = errors.New("certificate is outside its validity window")
	}
	if !opts.Managed && !replaceable(opts.CertFile, opts.KeyFile) {
		// The operator's own (possibly CA-issued) files: never overwrite them.
		return Result{}, fmt.Errorf("existing TLS certificate files are not usable and were not generated by CalSnap, so they are left untouched: %w", loadErr)
	}

	leaf, certPEM, keyPEM, err := generate(opts.Hosts, now)
	if err != nil {
		return Result{}, err
	}
	for _, path := range []string{opts.KeyFile, opts.CertFile} {
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			return Result{}, fmt.Errorf("create certificate directory: %w", err)
		}
	}
	// The key goes first: a crash between the two writes leaves a pair that
	// does not match, which loadUsable rejects on the next start.
	if err := writeAtomic(opts.KeyFile, keyPEM); err != nil {
		return Result{}, fmt.Errorf("write private key: %w", err)
	}
	if err := writeAtomic(opts.CertFile, certPEM); err != nil {
		return Result{}, fmt.Errorf("write certificate: %w", err)
	}
	return result(opts, leaf, true), nil
}

// replaceable reports whether the files may be overwritten in an unmanaged
// location: both are missing, or the certificate is one this package made.
func replaceable(certFile, keyFile string) bool {
	_, certErr := os.Stat(certFile)
	_, keyErr := os.Stat(keyFile)
	if errors.Is(certErr, os.ErrNotExist) && errors.Is(keyErr, os.ErrNotExist) {
		return true
	}
	data, err := os.ReadFile(certFile) //nolint:gosec // operator-configured path
	if err != nil {
		return false
	}
	block, _ := pem.Decode(data)
	if block == nil {
		return false
	}
	leaf, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		return false
	}
	return isGenerated(leaf)
}

// isGenerated recognizes the certificates made by generate.
func isGenerated(leaf *x509.Certificate) bool {
	return leaf.Subject.CommonName == subjectCommonName && bytes.Equal(leaf.RawSubject, leaf.RawIssuer)
}

// Fingerprint formats the SHA-256 of a DER certificate as colon-separated
// upper-case hex, for example "AB:CD:...".
func Fingerprint(der []byte) string {
	sum := sha256.Sum256(der)
	h := strings.ToUpper(hex.EncodeToString(sum[:]))
	parts := make([]string, 0, len(sum))
	for i := 0; i < len(h); i += 2 {
		parts = append(parts, h[i:i+2])
	}
	return strings.Join(parts, ":")
}

// LocalHosts lists names and addresses under which this machine is usually
// reached: localhost, its host name and the addresses of its interfaces.
func LocalHosts() []string {
	hosts := []string{"localhost", "127.0.0.1", "::1"}
	if name, err := os.Hostname(); err == nil && name != "" {
		hosts = append(hosts, name)
	}
	addrs, err := net.InterfaceAddrs()
	if err != nil {
		return hosts
	}
	for _, a := range addrs {
		if ipNet, ok := a.(*net.IPNet); ok && !ipNet.IP.IsLinkLocalUnicast() {
			hosts = append(hosts, ipNet.IP.String())
		}
	}
	return hosts
}

func result(opts Options, leaf *x509.Certificate, created bool) Result {
	return Result{
		CertFile:    opts.CertFile,
		KeyFile:     opts.KeyFile,
		Fingerprint: Fingerprint(leaf.Raw),
		NotAfter:    leaf.NotAfter,
		Created:     created,
	}
}

// loadPair parses the certificate and checks that the key belongs to it.
func loadPair(certFile, keyFile string) (*x509.Certificate, error) {
	pair, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		return nil, err
	}
	return x509.ParseCertificate(pair.Certificate[0])
}

// validFor reports whether the certificate is valid now and stays valid for at
// least the given duration.
func validFor(leaf *x509.Certificate, now time.Time, remaining time.Duration) bool {
	return !now.Before(leaf.NotBefore) && !now.Add(remaining).After(leaf.NotAfter)
}

func generate(hosts []string, now time.Time) (leaf *x509.Certificate, certPEM, keyPEM []byte, err error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("generate key: %w", err)
	}
	// 128 random bits, as recommended for certificate serial numbers.
	serial, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, nil, fmt.Errorf("generate serial number: %w", err)
	}
	dns, ips := splitHosts(hosts)
	tmpl := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: subjectCommonName, Organization: []string{"CalSnap"}},
		NotBefore:             now.Add(-clockSkew),
		NotAfter:              now.Add(validity),
		KeyUsage:              x509.KeyUsageDigitalSignature,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		DNSNames:              dns,
		IPAddresses:           ips,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("create certificate: %w", err)
	}
	leaf, err = x509.ParseCertificate(der)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("parse generated certificate: %w", err)
	}
	keyDER, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return nil, nil, nil, fmt.Errorf("marshal private key: %w", err)
	}
	certPEM = pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyPEM = pem.EncodeToMemory(&pem.Block{Type: "EC PRIVATE KEY", Bytes: keyDER})
	return leaf, certPEM, keyPEM, nil
}

// splitHosts separates IP addresses from DNS names and drops duplicates.
func splitHosts(hosts []string) (dns []string, ips []net.IP) {
	seen := make(map[string]bool, len(hosts))
	for _, raw := range hosts {
		h := strings.TrimSpace(raw)
		if h == "" || seen[strings.ToLower(h)] {
			continue
		}
		seen[strings.ToLower(h)] = true
		if ip := net.ParseIP(h); ip != nil {
			ips = append(ips, ip)
		} else {
			dns = append(dns, h)
		}
	}
	return dns, ips
}

// writeAtomic writes data to a temporary file next to path and renames it, so
// readers never see a partial file. os.CreateTemp makes the file private to
// the owner (mode 0600).
func writeAtomic(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	defer func() { _ = os.Remove(tmp.Name()) }() // no-op after a successful rename
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), path)
}
